server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/backend-service?options=-c%20timezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
    cache:
      type: redis

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  output:
    ansi:
      enabled: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    display-request-duration: true
  api-docs:
    path: /api-docs

jwt:
  access_key: ${JWT_ACCESS_KEY}
  refresh_key: ${JWT_REFRESH_KEY}

logging:
  level:
    org:
      hibernate:
        engine:
          jdbc:
            env:
              internal:
                JdbcEnvironmentInitiator: DEBUG
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

admin:
  admin_email: ${ADMIN_EMAIL}
  admin_password: ${ADMIN_PASSWORD}
